// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc-GK2848CQ1F3DThcZyVUrkky67vxGGg',
    appId: '1:394721279762:web:93e5402ed0cc3f17bc3dcb',
    messagingSenderId: '394721279762',
    projectId: 'pw-f-auth',
    authDomain: 'pw-f-auth.firebaseapp.com',
    storageBucket: 'pw-f-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQ9QdgHgxY9Aqj21mQtq7SdVJiiVZcfc',
    appId: '1:394721279762:android:0eac7bc1c1027005bc3dcb',
    messagingSenderId: '394721279762',
    projectId: 'pw-f-auth',
    storageBucket: 'pw-f-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUM1t3oAgxjZrequVAl4vweNcOed3XfD0',
    appId: '1:394721279762:ios:141c423f7c77ecbfbc3dcb',
    messagingSenderId: '394721279762',
    projectId: 'pw-f-auth',
    storageBucket: 'pw-f-auth.appspot.com',
    iosBundleId: 'com.example.pwAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUM1t3oAgxjZrequVAl4vweNcOed3XfD0',
    appId: '1:394721279762:ios:ca4b176fe9718ad5bc3dcb',
    messagingSenderId: '394721279762',
    projectId: 'pw-f-auth',
    storageBucket: 'pw-f-auth.appspot.com',
    iosBundleId: 'com.example.pwAuth.RunnerTests',
  );
}
